const translations = {
  ua: {
    pageHome: "Головна",
    pageAbout: "Про мене",
    pageWorks: "Портфоліо",
    pageCont: "Контакти",
    heroName: "Олексій Глазовий",
    btnCreateProject: "Створити проєкт",
    btnShowWorks: "Переглянути роботи",
    aboutMeTitle: "Про мене",
    aboutMep:
      "Займаюся версткою сайтів, використовую виключно ручний формат роботи з HTML, CSS та JavaScript. Без конструкторів. Переношу макети з Figma. Отримуєте чисті, швидкі та адаптивні вебсторінки. Уважно відтворюю деталі дизайну, перевіряю щоб усе коректно працювало на різних екранах та браузерах з максимальною швидкістю.",
    skillsOne: "Фронтенд-навички",
    skillsOneLiOne: "Адаптивний вебдизайн",
    skillsOneLiTwo: "Підтримка різних браузерів",
    skillsOneLiThree: "Робота за макетом, 1в1",
    skillsTwo: "Інструменти",
    skillsTwoLiOne: "HTML5",
    skillsTwoLiTwo: "CSS3",
    skillsTwoLiThree: "JavaScript",
    contactTitle: "Отримати консультацію",
  },
  en: {
    pageHome: "Home",
    pageAbout: "About Me",
    pageWorks: "Works",
    pageCont: "Contact",
    heroName: "Oleksii Hlazovyi",
    btnCreateProject: "Start a Project",
    btnShowWorks: "View Works",
  },
  pl: {
    pageHome: "Strona główna",
    pageAbout: "O mnie",
    pageWorks: "Portfolio",
    pageCont: "Kontakt",
    heroName: "Oleksij Hłazowy",
    btnCreateProject: "Stwórz projekt",
    btnShowWorks: "Zobacz prace",
  },
  ru: {
    pageHome: "Главная",
    pageAbout: "Обо мне",
    pageWorks: "Работы",
    pageCont: "Контакты",
    heroName: "Алексей Глазовой",
    btnCreateProject: "Создать проект",
    btnShowWorks: "Посмотреть работы",
  },
};
